version: '3.8'

services:
  nginx:
    image: nginx:stable-trixie
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev 
    environment:
      - NEXT_PUBLIC_API_URL=/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next